services:
  product-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: products
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - product-network

volumes:
  postgres_data:

networks:
  product-network:
    driver: bridge
